--- # mysql_playbook.yml
  - name: Remove  Mysql using Ansible
    hosts: web
    user: ec2-user
    become: yes
    connection: ssh

    tasks:     
      - name: Remove  MySQL Server packages
        yum: name=mysql  state=absent
      
