--- # remove_playbook.yml
  - name: Remove  Mysql using Ansible from ubuntu
    hosts: web
    become: yes
    connection: ssh

    tasks:
      - name: Remove  MySQL Server packages
        shell: sudo apt remove -y mysql-* && sudo sudo apt autoremove -y
